// AUTO-GENERATED CATALOG DATA
// Do not edit manually. Run build_catalog.py to update.

export const CATALOG_DATA = [
  {
    "id": 2,
    "type": "BIC",
    "collection": "Standard Bic Mixed Colors 2.0",
    "title": "Standard Bic - Black",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-01-A-US-ST-BL",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 3,
    "type": "BIC",
    "collection": "Standard Bic Mixed Colors 2.0",
    "title": "Standard Bic - Carolina",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-01-A-US-ST-CA",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 4,
    "type": "BIC",
    "collection": "Standard Bic Mixed Colors 2.0",
    "title": "Standard Bic - Grey",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-01-A-US-ST-GR",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 5,
    "type": "BIC",
    "collection": "Standard Bic Mixed Colors 2.0",
    "title": "Standard Bic - Army",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-01-A-US-ST-AR",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 6,
    "type": "BIC",
    "collection": "Standard Bic Mixed Colors 2.0",
    "title": "Standard Bic - Lavender",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-01-A-US-ST-LV",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 7,
    "type": "BIC",
    "collection": "Standard Bic Mixed Colors 2.0",
    "title": "Standard Bic - Magenta",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-01-A-US-ST-MG",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 8,
    "type": "BIC",
    "collection": "Standard Bic Mixed Colors 2.0",
    "title": "Standard Bic - Yellow",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-01-A-US-ST-YL",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 9,
    "type": "BIC",
    "collection": "Standard Bic Mixed Colors 2.0",
    "title": "Standard Bic - Orange",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-01-A-US-ST-OR",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 10,
    "type": "BIC",
    "collection": "Alice in Wonderland Bic",
    "title": "Alice in Wonderland Bic - Red Queen",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-AW-RQ",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 11,
    "type": "BIC",
    "collection": "Alice in Wonderland Bic",
    "title": "Alice in Wonderland Bic - Honey Hatter",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-AW-HH",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 12,
    "type": "BIC",
    "collection": "Alice in Wonderland Bic",
    "title": "Alice in Wonderland Bic - Sugar Cube",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-AW-SC",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 13,
    "type": "BIC",
    "collection": "Alice in Wonderland Bic",
    "title": "Alice in Wonderland Bic - Cockpaw",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-AW-CP",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 14,
    "type": "BIC",
    "collection": "Alice in Wonderland Bic",
    "title": "Alice in Wonderland Bic - Clockmaw",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-AW-CL",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 15,
    "type": "BIC",
    "collection": "Soul Speakers Bic",
    "title": "Soul Speakers Bic - Stay Positive",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-SS-SP",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 16,
    "type": "BIC",
    "collection": "Soul Speakers Bic",
    "title": "Soul Speakers Bic - Not Stoned Enough",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-SS-NS",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 17,
    "type": "BIC",
    "collection": "Soul Speakers Bic",
    "title": "Soul Speakers Bic - Lil Hippie",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-SS-LH",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 18,
    "type": "BIC",
    "collection": "Soul Speakers Bic",
    "title": "Soul Speakers Bic - Smoke the Flowers",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-SS-SF",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 19,
    "type": "BIC",
    "collection": "Soul Speakers Bic",
    "title": "Soul Speakers Bic - Stay Young",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-SS-SY",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 20,
    "type": "BIC",
    "collection": "Califari Strains Bic",
    "title": "Califari Strains Bic - Northern Lights",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-CF-NL",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 21,
    "type": "BIC",
    "collection": "Califari Strains Bic",
    "title": "Califari Strains Bic - GS Cookies",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-CF-GC",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 22,
    "type": "BIC",
    "collection": "Califari Strains Bic",
    "title": "Califari Strains Bic - Sour Diesel",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-CF-SD",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 23,
    "type": "BIC",
    "collection": "Califari Strains Bic",
    "title": "Califari Strains Bic - Grand Daddy Purple",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-CF-GP",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 24,
    "type": "BIC",
    "collection": "Califari Strains Bic",
    "title": "Califari Strains Bic - Pineapple Express",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-CF-PE",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 25,
    "type": "BIC",
    "collection": "Shroomies Bic",
    "title": "Shroomies Bic - Double Dose",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-SH-DD",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 26,
    "type": "BIC",
    "collection": "Shroomies Bic",
    "title": "Shroomies Bic - Night Trippin",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-SH-NT",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 27,
    "type": "BIC",
    "collection": "Shroomies Bic",
    "title": "Shroomies Bic - Fun Guy",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-SH-FG",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 28,
    "type": "BIC",
    "collection": "Shroomies Bic",
    "title": "Shroomies Bic - Golden Teacher",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-SHGT",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 29,
    "type": "BIC",
    "collection": "Shroomies Bic",
    "title": "Shroomies Bic - Toadstool",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-SH-TS",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 30,
    "type": "BIC",
    "collection": "Four Twenty Bic",
    "title": "Four Twenty Bic - Beach Dance",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-FT-BD",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 31,
    "type": "BIC",
    "collection": "Four Twenty Bic",
    "title": "Four Twenty Bic - Electric Haze",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-FT-EH",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 32,
    "type": "BIC",
    "collection": "Four Twenty Bic",
    "title": "Four Twenty Bic - Rasta",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-FT-RA",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 33,
    "type": "BIC",
    "collection": "Four Twenty Bic",
    "title": "Four Twenty Bic - Tropical Groove",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-FT-TG",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 34,
    "type": "BIC",
    "collection": "Four Twenty Bic",
    "title": "Four Twenty Bic - Wild",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-FT-WD",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 35,
    "type": "BIC",
    "collection": "Trippy Hippy Bic",
    "title": "Trippy Hippy Bic - Happy Hippy",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-TH-HH",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 36,
    "type": "BIC",
    "collection": "Trippy Hippy Bic",
    "title": "Trippy Hippy Bic - Road Trip",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-TH-RT",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 37,
    "type": "BIC",
    "collection": "Trippy Hippy Bic",
    "title": "Trippy Hippy Bic - Van Life",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-TH-RT",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 38,
    "type": "BIC",
    "collection": "Trippy Hippy Bic",
    "title": "Trippy Hippy Bic - Leafy",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-TH-LF",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 39,
    "type": "BIC",
    "collection": "Trippy Hippy Bic",
    "title": "Trippy Hippy Bic - Tie Dye",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-TH-TD",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 40,
    "type": "BIC",
    "collection": "Trippy Hippy Bic",
    "title": "Trippy Hippy Bic - Peace of Life",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-TH-PL",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 41,
    "type": "BIC",
    "collection": "Vibrant Visions Bic",
    "title": "Vibrant Visions Bic - Hue Harmony",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-VV-HH",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 42,
    "type": "BIC",
    "collection": "Vibrant Visions Bic",
    "title": "Vibrant Visions Bic - Earth Echo",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-VV-EE",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 43,
    "type": "BIC",
    "collection": "Vibrant Visions Bic",
    "title": "Vibrant Visions Bic - Cosmic Creation",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-VV-CR",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 44,
    "type": "BIC",
    "collection": "Vibrant Visions Bic",
    "title": "Vibrant Visions Bic - Color Crescendo",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-VV-CC",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 45,
    "type": "BIC",
    "collection": "Vibrant Visions Bic",
    "title": "Vibrant Visions Bic - Vibrant Vision",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-VV-VV",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 46,
    "type": "BIC",
    "collection": "Glow in the Dark Bic",
    "title": "Glow in the Dark Bic - Clear",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-GL-CL",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 47,
    "type": "BIC",
    "collection": "Glow in the Dark Bic",
    "title": "Glow in the Dark Bic - Green",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-GL-GN",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 48,
    "type": "BIC",
    "collection": "Glow in the Dark Bic",
    "title": "Glow in the Dark Bic - Blue",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-GL-BU",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 49,
    "type": "BIC",
    "collection": "Glow in the Dark Bic",
    "title": "Glow in the Dark Bic - Pink",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-GL-PK",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 50,
    "type": "BIC",
    "collection": "Glow in the Dark Bic",
    "title": "Glow in the Dark Bic - Yellow",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-GL-YL",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 51,
    "type": "BIC",
    "collection": "Sparkle Bic",
    "title": "Sparkle Bic - Green",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-SP-GN",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 52,
    "type": "BIC",
    "collection": "Sparkle Bic",
    "title": "Sparkle Bic - Clear",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-SP-CL",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 53,
    "type": "BIC",
    "collection": "Sparkle Bic",
    "title": "Sparkle Bic - Blue",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-SP-BU",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 54,
    "type": "BIC",
    "collection": "Sparkle Bic",
    "title": "Sparkle Bic - Purple",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-SP-PU",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 55,
    "type": "BIC",
    "collection": "Sparkle Bic",
    "title": "Sparkle Bic - Pink",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-SP-PK",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 56,
    "type": "BIC",
    "collection": "Sparkle Bic",
    "title": "Sparkle Bic - Black",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-SP-BL",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 57,
    "type": "BIC",
    "collection": "Hemp Plastic Bic",
    "title": "Hemp Plastic Bic - Charcoal",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-04-H-US-HP-CH",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 58,
    "type": "BIC",
    "collection": "Hemp Plastic Bic",
    "title": "Hemp Plastic Bic - Sage",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-04-H-US-HP-SG",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 59,
    "type": "BIC",
    "collection": "Hemp Plastic Bic",
    "title": "Hemp Plastic Bic - Plum",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-04-H-US-HP-PL",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 60,
    "type": "BIC",
    "collection": "Hemp Plastic Bic",
    "title": "Hemp Plastic Bic - Mustard",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-04-H-US-HP-MS",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 61,
    "type": "BIC",
    "collection": "Hemp Plastic Bic",
    "title": "Hemp Plastic Bic - Oatmeal",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-04-H-US-HP-OM",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 62,
    "type": "BIC",
    "collection": "Rip N Dip Bic - Lord Savior",
    "title": "Rip N Dip - Lord Savior - Welcome to Heck",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-RDO-WH",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 63,
    "type": "BIC",
    "collection": "Rip N Dip Bic - Lord Savior",
    "title": "Rip N Dip - Lord Savior - Psychedelic",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-RDO-PS",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 64,
    "type": "BIC",
    "collection": "Rip N Dip Bic - Lord Savior",
    "title": "Rip N Dip - Lord Savior - F*ckin F*ck",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-RDO-FF",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 65,
    "type": "BIC",
    "collection": "Rip N Dip Bic - Lord Savior",
    "title": "Rip N Dip - Lord Savior - Lord Nermal",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-RDO-LN",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 66,
    "type": "BIC",
    "collection": "Rip N Dip Bic - Lord Savior",
    "title": "Rip N Dip - Lord Savior - Lord Savior",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-RDO-LS",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 67,
    "type": "BIC",
    "collection": "Rip N Dip Bic - Lord Nermal",
    "title": "Rip N Dip Bic - Lord Nermal - Nermal S. Thompson",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-RDT-NT",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 68,
    "type": "BIC",
    "collection": "Rip N Dip Bic - Lord Nermal",
    "title": "Rip N Dip Bic - Lord Nermal - Nermal Devil",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-RDT-ND",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 69,
    "type": "BIC",
    "collection": "Rip N Dip Bic - Lord Nermal",
    "title": "Rip N Dip Bic - Lord Nermal - Blue Nermal",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-RDT-BN",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 70,
    "type": "BIC",
    "collection": "Rip N Dip Bic - Lord Nermal",
    "title": "Rip N Dip Bic - Lord Nermal - Nermal Lover",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-RDT-NL",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 71,
    "type": "BIC",
    "collection": "Rip N Dip Bic - Lord Nermal",
    "title": "Rip N Dip Bic - Lord Nermal - Lord Alien",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-01-A-US-RDT-LA",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 72,
    "type": "BIC",
    "collection": "Naughty Needlepoints",
    "title": "Naughty Needlepoints - Puff Puff Pass",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-NN-PP",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 73,
    "type": "BIC",
    "collection": "Naughty Needlepoints",
    "title": "Naughty Needlepoints - Say Perhaps to Drugs",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-NN-SP",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 74,
    "type": "BIC",
    "collection": "Naughty Needlepoints",
    "title": "Naughty Needlepoints - C U Next Tuesday",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-NN-CU",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 75,
    "type": "BIC",
    "collection": "Naughty Needlepoints",
    "title": "Naughty Needlepoints - Home is Where the Weed At",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-NN-HW",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 76,
    "type": "BIC",
    "collection": "Naughty Needlepoints",
    "title": "Naughty Needlepoints - F*ck Me Like the Government",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-01-A-US-NN-FM",
    "size": "3.125\"x1.75\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 77,
    "type": "Clipper",
    "collection": "Standard Clipper Mixed Colors",
    "title": "Standard Clipper - Black",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-02-A-US-ST-BL",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 78,
    "type": "Clipper",
    "collection": "Standard Clipper Mixed Colors",
    "title": "Standard Clipper - Carolina",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-02-A-US-ST-CA",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 79,
    "type": "Clipper",
    "collection": "Standard Clipper Mixed Colors",
    "title": "Standard Clipper - Grey",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-02-A-US-ST-GR",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 80,
    "type": "Clipper",
    "collection": "Standard Clipper Mixed Colors",
    "title": "Standard Clipper - Army",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-02-A-US-ST-AR",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 81,
    "type": "Clipper",
    "collection": "Standard Clipper Mixed Colors",
    "title": "Standard Clipper - Lavender",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-02-A-US-ST-LV",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 82,
    "type": "Clipper",
    "collection": "Standard Clipper Mixed Colors",
    "title": "Standard Clipper - Magenta",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-02-A-US-ST-MG",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 83,
    "type": "Clipper",
    "collection": "Standard Clipper Mixed Colors",
    "title": "Standard Clipper - Yellow",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-ST-YL",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 84,
    "type": "Clipper",
    "collection": "Standard Clipper Mixed Colors",
    "title": "Standard Clipper - Orange",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-02-A-US-ST-OR",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 85,
    "type": "Clipper",
    "collection": "Alice in Wonderland Clipper",
    "title": "Alice in Wonderland Clipper - Red Queen",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-AW-RQ",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 86,
    "type": "Clipper",
    "collection": "Alice in Wonderland Clipper",
    "title": "Alice in Wonderland Clipper - Honey Hatter",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-AW-HH",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 87,
    "type": "Clipper",
    "collection": "Alice in Wonderland Clipper",
    "title": "Alice in Wonderland Clipper - Sugar Cube",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-AW-SC",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 88,
    "type": "Clipper",
    "collection": "Alice in Wonderland Clipper",
    "title": "Alice in Wonderland Clipper - Cockpaw",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-AW-CP",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 89,
    "type": "Clipper",
    "collection": "Alice in Wonderland Clipper",
    "title": "Alice in Wonderland Clipper - Clockmaw",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-AW-CL",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 90,
    "type": "Clipper",
    "collection": "Soul Speakers Clipper",
    "title": "Soul Speakers Clipper - Stay Positive",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-SS-SP",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 91,
    "type": "Clipper",
    "collection": "Soul Speakers Clipper",
    "title": "Soul Speakers Clipper - Not Stoned Enough",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-SS-NS",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 92,
    "type": "Clipper",
    "collection": "Soul Speakers Clipper",
    "title": "Soul Speakers Clipper - Lil Hippie",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-SS-LH",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 93,
    "type": "Clipper",
    "collection": "Soul Speakers Clipper",
    "title": "Soul Speakers Clipper - Smoke the Flowers",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-SS-SF",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 94,
    "type": "Clipper",
    "collection": "Soul Speakers Clipper",
    "title": "Soul Speakers Clipper - Stay Young",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-SS-SY",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 95,
    "type": "Clipper",
    "collection": "Califari Strains Clipper",
    "title": "Califari Strains Clipper - Northern Lights",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-CF-NL",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 96,
    "type": "Clipper",
    "collection": "Califari Strains Clipper",
    "title": "Califari Strains Clipper - GS Cookies",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-CF-GC",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 97,
    "type": "Clipper",
    "collection": "Califari Strains Clipper",
    "title": "Califari Strains Clipper - Sour Diesel",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-CF-SD",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 98,
    "type": "Clipper",
    "collection": "Califari Strains Clipper",
    "title": "Califari Strains Clipper - Grand Daddy Purple",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-CF-GP",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 99,
    "type": "Clipper",
    "collection": "Califari Strains Clipper",
    "title": "Califari Strains Clipper - Pineapple Express",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-CF-PE",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 100,
    "type": "Clipper",
    "collection": "Shroomies Clipper",
    "title": "Shroomies Clipper - Double Dose",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-SH-DD",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 101,
    "type": "Clipper",
    "collection": "Shroomies Clipper",
    "title": "Shroomies Clipper - Night Trippin",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-SH-NT",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 102,
    "type": "Clipper",
    "collection": "Shroomies Clipper",
    "title": "Shroomies Clipper - Fun Guy",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-SH-FG",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 103,
    "type": "Clipper",
    "collection": "Shroomies Clipper",
    "title": "Shroomies Clipper - Golden Teacher",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-SH-GT",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 104,
    "type": "Clipper",
    "collection": "Shroomies Clipper",
    "title": "Shroomies Clipper - Toadstool",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-SH-TS",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 105,
    "type": "Clipper",
    "collection": "Four Twenty Clipper",
    "title": "Four Twenty Clipper - Beach Dance",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-FT-BD",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 106,
    "type": "Clipper",
    "collection": "Four Twenty Clipper",
    "title": "Four Twenty Clipper - Electric Haze",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-FT-EH",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 107,
    "type": "Clipper",
    "collection": "Four Twenty Clipper",
    "title": "Four Twenty Clipper - Rasta",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-FT-RA",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 108,
    "type": "Clipper",
    "collection": "Four Twenty Clipper",
    "title": "Four Twenty Clipper - Tropical Groove",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-FT-TG",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 109,
    "type": "Clipper",
    "collection": "Four Twenty Clipper",
    "title": "Four Twenty Clipper - Wild",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-02-A-US-FT-WD",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 110,
    "type": "Clipper",
    "collection": "Trippy Hippy Clipper",
    "title": "Trippy Hippy Clipper - Happy Hippy",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-TH-HH",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 111,
    "type": "Clipper",
    "collection": "Trippy Hippy Clipper",
    "title": "Trippy Hippy Clipper - Road Trip",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-TH-RT",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 112,
    "type": "Clipper",
    "collection": "Trippy Hippy Clipper",
    "title": "Trippy Hippy Clipper - Leafy",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-TH-LF",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 113,
    "type": "Clipper",
    "collection": "Trippy Hippy Clipper",
    "title": "Trippy Hippy Clipper - Tie Dye",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-TH-TD",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 114,
    "type": "Clipper",
    "collection": "Trippy Hippy Clipper",
    "title": "Trippy Hippy Clipper - Peace of Life",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-TH-PL",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 115,
    "type": "Clipper",
    "collection": "Vibrant Visions Clipper",
    "title": "Vibrant Visions Clipper - Hue Harmony",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-VV-HH",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 116,
    "type": "Clipper",
    "collection": "Vibrant Visions Clipper",
    "title": "Vibrant Visions Clipper - Earth Echo",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-VV-EE",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 117,
    "type": "Clipper",
    "collection": "Vibrant Visions Clipper",
    "title": "Vibrant Visions Clipper - Cosmic Creation",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-VV-CR",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 118,
    "type": "Clipper",
    "collection": "Vibrant Visions Clipper",
    "title": "Vibrant Visions Clipper - Color Crescendo",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-VV-CC",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 119,
    "type": "Clipper",
    "collection": "Vibrant Visions Clipper",
    "title": "Vibrant Visions Clipper - Vibrant Vision",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-VV-VV",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 120,
    "type": "Clipper",
    "collection": "Glow in the Dark Clipper",
    "title": "Glow in the Dark Clipper - Clear",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-GL-CL",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 121,
    "type": "Clipper",
    "collection": "Glow in the Dark Clipper",
    "title": "Glow in the Dark Clipper - Green",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-GL-GN",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 122,
    "type": "Clipper",
    "collection": "Glow in the Dark Clipper",
    "title": "Glow in the Dark Clipper - Blue",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-GL-BU",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 123,
    "type": "Clipper",
    "collection": "Glow in the Dark Clipper",
    "title": "Glow in the Dark Clipper - Pink",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-GL-PK",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 124,
    "type": "Clipper",
    "collection": "Glow in the Dark Clipper",
    "title": "Glow in the Dark Clipper - Yellow",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-GL-YL",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 125,
    "type": "Clipper",
    "collection": "Sparkle Clipper",
    "title": "Sparkle Clipper - Green",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-SP-GN",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 126,
    "type": "Clipper",
    "collection": "Sparkle Clipper",
    "title": "Sparkle Clipper - Clear",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-SP-CL",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 127,
    "type": "Clipper",
    "collection": "Sparkle Clipper",
    "title": "Sparkle Clipper - Blue",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-SP-BU",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 128,
    "type": "Clipper",
    "collection": "Sparkle Clipper",
    "title": "Sparkle Clipper - Purple",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-SP-PU",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 129,
    "type": "Clipper",
    "collection": "Sparkle Clipper",
    "title": "Sparkle Clipper - Pink",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-SP-PK",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 130,
    "type": "Clipper",
    "collection": "Sparkle Clipper",
    "title": "Sparkle Clipper - Black",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-02-A-US-SP-BL",
    "size": "2.875\"x1.375\"x0.75\"",
    "weight": "0.8 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 131,
    "type": "Mini Bic",
    "collection": "Standard Mini Bic Mixed Colors",
    "title": "Standard Mini Bic - Black",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-03-A-US-ST-BL",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 132,
    "type": "Mini Bic",
    "collection": "Standard Mini Bic Mixed Colors",
    "title": "Standard Mini Bic - Carolina",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-03-A-US-ST-CA",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 133,
    "type": "Mini Bic",
    "collection": "Standard Mini Bic Mixed Colors",
    "title": "Standard Mini Bic - Grey",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-03-A-US-ST-GR",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 134,
    "type": "Mini Bic",
    "collection": "Standard Mini Bic Mixed Colors",
    "title": "Standard Mini Bic - Army",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-03-A-US-ST-AR",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 135,
    "type": "Mini Bic",
    "collection": "Standard Mini Bic Mixed Colors",
    "title": "Standard Mini Bic - Lavender",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-03-A-US-ST-LV",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 136,
    "type": "Mini Bic",
    "collection": "Standard Mini Bic Mixed Colors",
    "title": "Standard Mini Bic - Magenta",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-03-A-US-ST-MG",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 137,
    "type": "Mini Bic",
    "collection": "Standard Mini Bic Mixed Colors",
    "title": "Standard Mini Bic - Yellow",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-03-A-US-ST-YL",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 138,
    "type": "Mini Bic",
    "collection": "Standard Mini Bic Mixed Colors",
    "title": "Standard Mini Bic - Orange",
    "brand": "Toker Poker",
    "msrp": 10.99,
    "dist": 2.8,
    "amazon": 9.99,
    "sku": "RTL-03-A-US-ST-OR",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 139,
    "type": "Mini Bic",
    "collection": "Glow in the Dark Mini Bic",
    "title": "Glow in the Dark Mini Bic - Clear",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-03-A-US-GL-CL",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 140,
    "type": "Mini Bic",
    "collection": "Glow in the Dark Mini Bic",
    "title": "Glow in the Dark Mini Bic - Green",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-03-A-US-GL-GN",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 141,
    "type": "Mini Bic",
    "collection": "Glow in the Dark Mini Bic",
    "title": "Glow in the Dark Mini Bic - Blue",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 0.0,
    "sku": "RTL-03-A-US-GL-BU",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 142,
    "type": "Mini Bic",
    "collection": "Glow in the Dark Mini Bic",
    "title": "Glow in the Dark Mini Bic - Pink",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-03-A-US-GL-PK",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 143,
    "type": "Mini Bic",
    "collection": "Glow in the Dark Mini Bic",
    "title": "Glow in the Dark Mini Bic - Yellow",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-03-A-US-GL-YL",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": true,
    "color": "#1a1a1a"
  },
  {
    "id": 144,
    "type": "Mini Bic",
    "collection": "Sparkle Mini Bic",
    "title": "Sparkle Mini Bic - Green",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-03-A-US-SP-GN",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 145,
    "type": "Mini Bic",
    "collection": "Sparkle Mini Bic",
    "title": "Sparkle Mini Bic - Clear",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-03-A-US-SP-CL",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 146,
    "type": "Mini Bic",
    "collection": "Sparkle Mini Bic",
    "title": "Sparkle Mini Bic - Blue",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-03-A-US-SP-BU",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 147,
    "type": "Mini Bic",
    "collection": "Sparkle Mini Bic",
    "title": "Sparkle Mini Bic - Purple",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-03-A-US-SP-PU",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 148,
    "type": "Mini Bic",
    "collection": "Sparkle Mini Bic",
    "title": "Sparkle Mini Bic - Pink",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-03-A-US-SP-PK",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 149,
    "type": "Mini Bic",
    "collection": "Sparkle Mini Bic",
    "title": "Sparkle Mini Bic - Black",
    "brand": "Toker Poker",
    "msrp": 12.99,
    "dist": 4.2,
    "amazon": 13.99,
    "sku": "RTL-03-A-US-SP-BL",
    "size": "2.25\"x1.75\"x0.5\"",
    "weight": "0.4 oz",
    "available": false,
    "color": "#1a1a1a"
  },
  {
    "id": 154,
    "type": "Mini Bic",
    "collection": "Sparkle Mini Bic",
    "title": "",
    "brand": "nan",
    "msrp": 0.0,
    "dist": 0.0,
    "amazon": 0.0,
    "sku": "N/A",
    "size": "Standard",
    "weight": "0.8 oz",
    "available": true,
    "color": "#1a1a1a"
  }
];
